### ISSUE TITLE
Shellcheck doesn't like `[ -f "${queryArg}" -a -z "${fileArg}" ]`

### ISSUE THREAD

**Issue by grahampugh** [brunerd/ljt#2]
It's just Shellcheck's opinion, of course... 
https://www.shellcheck.net/wiki/SC2166

It prefers `[ -f "${queryArg}" ] && [ -z "${fileArg}" ]`

**Comment by brunerd** [comment]
Well, isn't shellcheck just a persnickety little so and so... :> I will admit I did it because chains of `&&` don't always behave like you expect and using `-a` was a way to easily make those two criteria a single compound statement. Anyway I suppose I could have put it in a `()` subshell, but that's unnecessary overhead. Anyway it's a one-line `if` statement using `&&` now... may shellcheck smile upon me.

Thanks! 😁

Oh yeah, I also needed to go back to good ol' she-bang paths that don't use `env` why? When an alternate `bash` or `zsh` is installed it messes up the ability to pipe in data, so back to the direct paths.
